version: "3"

services:
  nginx:
    image: nginx
    restart: always
    command: [ nginx, '-g', 'daemon off;' ]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080

  api-gateway:
    build:
      context: api-gateway-service
      dockerfile: Dockerfile
    image: usample-api-gateway
    restart: always
    env_file: api-gateway-service/.env
    ports:
      - "1337:1337"