version: "3"

services:
  nginx:
    image: nginx
    restart: always
    command: [ nginx, '-g', 'daemon off;' ]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server
    volumes:
      - redis_data:/data
      - ./auth-service/configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  database:
    image: postgres:alpine
    env_file: postgres/.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data

  api-gateway:
    build:
      context: api-gateway-service
      dockerfile: Dockerfile
    image: usample-api-gateway
    restart: always
    env_file: api-gateway-service/.env
    ports:
      - "1337:1337"

  auth:
    build:
      context: auth-service
      dockerfile: Dockerfile
    image: usample-auth
    restart: always
    env_file: auth-service/.env
    ports:
      - "13371:13371"

  users:
    build:
      context: users-service
      dockerfile: Dockerfile
    image: usample-users
    restart: always
    env_file: users-service/.env
    ports:
      - "13372:13372"


volumes:
  redis_data:
  db: